-- Inserir Usuários
INSERT INTO users (name, description, email, password) VALUES ('Alice Johnson', 'Especialista em telemedicina com ampla experiência em tecnologias de saúde.', 'alice.johnson@example.com', 'password123');
INSERT INTO users (name, description, email, password) VALUES ('Bob Smith', 'Consultor em dispositivos vestíveis e tecnologias de monitoramento de saúde.', 'bob.smith@example.com', 'password456');
INSERT INTO users (name, description, email, password) VALUES ('Charlie Brown', 'Pesquisador em inteligência artificial e suas aplicações na medicina.', 'charlie.brown@example.com', 'password789');
INSERT INTO users (name, description, email, password) VALUES ('Diana Prince', 'Especialista em reabilitação médica e uso de realidade virtual em tratamentos.', 'diana.prince@example.com', 'password101');

-- Inserir Posts
INSERT INTO posts (user_id, title, description) VALUES (1, 'A Revolução da Telemedicina', 'A telemedicina tem transformado o atendimento à saúde, permitindo consultas médicas a distância e monitoramento remoto de pacientes. Descubra como essa tecnologia está moldando o futuro da medicina e melhorando o acesso a cuidados médicos.');
INSERT INTO posts (user_id, title, description) VALUES (2, 'Wearables: Monitorando Sua Saúde em Tempo Real', 'Dispositivos vestíveis, como smartwatches e fitness trackers, estão se tornando essenciais para monitorar a saúde. Saiba como essas tecnologias podem ajudá-lo a acompanhar sua atividade física, qualidade do sono e sinais vitais.');
INSERT INTO posts (user_id, title, description) VALUES (3, 'Inteligência Artificial no Diagnóstico de Doenças', 'A inteligência artificial está revolucionando o diagnóstico de doenças, desde a detecção precoce de câncer até a previsão de surtos de doenças infecciosas. Modelos de aprendizado de máquina são capazes de analisar grandes volumes de dados médicos, identificar padrões e fornecer diagnósticos precisos mais rapidamente do que os métodos tradicionais. Com a IA, médicos podem oferecer tratamentos mais personalizados e eficazes, aumentando as chances de sucesso terapêutico. Além disso, a IA está ajudando a reduzir os custos de saúde ao automatizar tarefas repetitivas e melhorar a eficiência operacional dos hospitais. Esses avanços estão transformando a medicina e trazendo esperança para milhões de pacientes ao redor do mundo.');
INSERT INTO posts (user_id, title, description) VALUES (4, 'Aplicativos de Saúde: Gerenciando Seu Bem-Estar', 'Com a proliferação de aplicativos de saúde, gerenciar seu bem-estar nunca foi tão fácil. De dietas personalizadas a programas de exercícios, veja como esses aplicativos podem melhorar sua saúde diária.');
INSERT INTO posts (user_id, title, description) VALUES (2, 'Blockchain na Saúde: Segurança e Privacidade de Dados', 'A tecnologia blockchain está sendo explorada para garantir a segurança e privacidade dos dados de saúde. Entenda como essa tecnologia pode proteger suas informações médicas sensíveis e melhorar a interoperabilidade dos sistemas de saúde.');
INSERT INTO posts (user_id, title, description) VALUES (3, 'Realidade Virtual na Reabilitação Médica', 'A realidade virtual está sendo usada para tratar pacientes em reabilitação, proporcionando um ambiente controlado e envolvente para a recuperação. Pacientes com lesões graves, como acidentes vasculares cerebrais ou traumas físicos, estão se beneficiando dessas novas terapias. A tecnologia permite criar simulações realistas que ajudam os pacientes a praticar movimentos e atividades diárias, acelerando o processo de reabilitação. Além disso, a RV pode ser utilizada para tratar distúrbios psicológicos, como fobias e transtorno de estresse pós-traumático, expondo gradualmente os pacientes a situações controladas. Com a evolução contínua da RV, espera-se que mais aplicações inovadoras surjam, tornando a reabilitação médica mais eficaz e acessível a todos.');
INSERT INTO posts (user_id, title, description) VALUES (4, 'Inovações na Realidade Virtual para Reabilitação Neurológica', 'Recentes inovações em realidade virtual estão transformando a reabilitação neurológica. Novas tecnologias permitem simulações mais precisas e interativas, focadas em melhorar a função cognitiva e motora. Esses avanços estão ajudando pacientes a superar desafios pós-acidente vascular cerebral e outras condições neurológicas com abordagens terapêuticas mais envolventes e eficazes.');
INSERT INTO posts (user_id, title, description) VALUES (1, 'Realidade Virtual e Reabilitação Ortopédica: Novas Fronteiras', 'A realidade virtual está abrindo novas possibilidades na reabilitação ortopédica, oferecendo soluções inovadoras para a recuperação de fraturas e cirurgias ortopédicas. Com ambientes virtuais que simulam movimentos específicos e exercícios, os pacientes podem realizar terapias de forma mais interativa e personalizada, acelerando a recuperação e melhorando os resultados clínicos.');
INSERT INTO posts (user_id, title, description) VALUES (2, 'Realidade Virtual para Reabilitação Psicológica: Superando Transtornos de Ansiedade', 'A realidade virtual está se mostrando uma ferramenta eficaz para a reabilitação psicológica, especialmente no tratamento de transtornos de ansiedade. Simulações controladas e expostos gradualmente ajudam os pacientes a enfrentar e superar suas ansiedades em um ambiente seguro. Essa abordagem permite tratamentos personalizados e melhora a eficácia das terapias psicológicas, oferecendo uma nova esperança para aqueles que lutam contra esses distúrbios.');

-- Inserir Comentários
INSERT INTO comments (user_id, text, post_id) VALUES (1, 'Excelente post! Muito informativo.', 1);
INSERT INTO comments (user_id, text, post_id) VALUES (2, 'Concordo com o que foi dito, mas gostaria de mais detalhes sobre o assunto.', 1);
INSERT INTO comments (user_id, text, post_id) VALUES (3, 'Ótima explicação, mas achei que a conclusão poderia ser mais detalhada.', 2);
INSERT INTO comments (user_id, text, post_id) VALUES (4, 'Achei o artigo muito útil. Vou aplicar essas dicas no meu projeto.', 2);
INSERT INTO comments (user_id, text, post_id) VALUES (3, 'Isso realmente faz sentido! Vou revisar o que aprendi aqui.', 3);
INSERT INTO comments (user_id, text, post_id) VALUES (4, 'Preciso de mais exemplos práticos para entender melhor o conceito.', 3);
INSERT INTO comments (user_id, text, post_id) VALUES (1, 'Eu discordo de algumas partes, mas o texto é bem escrito.', 4);
INSERT INTO comments (user_id, text, post_id) VALUES (2, 'Gostei do post. Seria interessante ver uma continuação sobre este tema.', 4);
INSERT INTO comments (user_id, text, post_id) VALUES (4, 'Muito bom, gostei da abordagem!', 5);
INSERT INTO comments (user_id, text, post_id) VALUES (1, 'Interessante, gostaria de saber mais sobre como aplicá-lo.', 5);
INSERT INTO comments (user_id, text, post_id) VALUES (2, 'A análise foi precisa, mas há espaço para mais detalhes.', 6);
INSERT INTO comments (user_id, text, post_id) VALUES (3, 'Gostei muito das informações fornecidas, obrigado.', 6);
INSERT INTO comments (user_id, text, post_id) VALUES (4, 'O post oferece boas informações, mas eu esperava mais sobre a aplicação prática.', 7);
INSERT INTO comments (user_id, text, post_id) VALUES (1, 'Excelente conteúdo, seria ótimo ter um tutorial passo a passo.', 7);
INSERT INTO comments (user_id, text, post_id) VALUES (2, 'Ótimo post, aguardo ansiosamente pela continuação.', 8);
INSERT INTO comments (user_id, text, post_id) VALUES (3, 'Bom artigo, mas a discussão sobre casos de uso poderia ser mais aprofundada.', 8);
INSERT INTO comments (user_id, text, post_id) VALUES (4, 'Muito útil, especialmente para quem está começando.', 9);
INSERT INTO comments (user_id, text, post_id) VALUES (1, 'As informações são boas, mas seria interessante adicionar exemplos de casos reais.', 9);
